import * as THREE from 'three';
import {setupFoundation} from './foundation.mjs';
import {emptyState,loadState,saveState,validateState} from './state.mjs';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {DRACOLoader} from 'three/addons/loaders/DRACOLoader.js';
const $=id=>document.getElementById(id);
const viewport=$('viewport'),scene=new THREE.Scene();
let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});}catch(e){$('loadText').textContent='جهازك لا يتيح WebGL. جرّب متصفح Chrome حديثًا.';throw e;}
renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.7));renderer.setSize(viewport.clientWidth,viewport.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.localClippingEnabled=true;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;viewport.prepend(renderer.domElement);
const camera=new THREE.PerspectiveCamera(36,viewport.clientWidth/viewport.clientHeight,.001,200);camera.position.set(0,1,10);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.minDistance=.08;controls.maxDistance=35;controls.autoRotateSpeed=.7;
scene.add(new THREE.HemisphereLight(0xeaf7ff,0x31434c,2.4));
for(const [position,color,intensity] of [[[5,7,8],0xfff5e1,3], [[-6,4,-5],0x7bdfdc,2.2],[[0,-4,6],0xffffff,.7]]){let light=new THREE.DirectionalLight(color,intensity);light.position.set(...position);scene.add(light);}
const draco=new DRACOLoader().setDecoderPath('./vendor/examples/jsm/libs/draco/gltf/');draco.setWorkerLimit(2);const loader=new GLTFLoader().setDRACOLoader(draco);
const clipPlane=new THREE.Plane(new THREE.Vector3(0,-1,0),0),raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();
const colors={bone:'#e5d8b7',organ:'#c56b6a',brain:'#daae9a',skin:'#d7a898',muscle:'#b85659',vessel:'#ec7770'};
const kindAr={bone:'الهيكل العظمي',organ:'الأعضاء الداخلية',brain:'الدماغ',skin:'سطح الجسم',muscle:'عضلات الذراع',vessel:'أوعية الذراع'};
const translated=[['clavicle','الترقوة'],['scapula','لوح الكتف'],['humerus','عظم العضد'],['radius','الكعبرة'],['ulna','الزند'],['femur','عظم الفخذ'],['tibia','الظنبوب'],['fibula','الشظية'],['patella','الرضفة'],['atlas','الأطلس — الفقرة الأولى'],['axis','المحور — الفقرة الثانية'],['manubrium','قبضة القص'],['sternum','عظم القص'],['mandible','الفك السفلي'],['maxilla','الفك العلوي'],['frontal','العظم الجبهي'],['parietal','العظم الجداري'],['occipital','العظم القذالي'],['temporal','العظم الصدغي'],['sphenoid','العظم الوتدي'],['ethmoid','العظم الغربالي'],['zygomatic','العظم الوجني'],['vomer','العظم الميكعي'],['sacrum','العجز'],['coccyx','العصعص'],['hip bone','عظم الحوض'],['rib','ضلع'],['cervical vertebra','فقرة عنقية'],['thoracic vertebra','فقرة صدرية'],['lumbar vertebra','فقرة قطنية'],['heart','القلب'],['lungs','الرئة'],['liver','الكبد'],['kidneys','الكلية'],['stomach','المعدة'],['intestines','الأمعاء'],['brain','الدماغ'],['skin','سطح الجسم'],['deltoid','العضلة الدالية'],['biceps','العضلة ذات الرأسين'],['triceps','العضلة ثلاثية الرؤوس'],['brachioradialis','العضلة العضدية الكعبرية'],['brachialis','العضلة العضدية'],['flexor carpi radialis','مثنية الرسغ الكعبرية'],['brachial artery','الشريان العضدي'],['radial artery','الشريان الكعبري'],['ulnar artery','الشريان الزندي'],['basilic vein','الوريد البازيلي'],['cephalic vein','الوريد الرأسي']];
const notes={
clavicle:{description:'عظمة منحنية على شكل S تربط الطرف العلوي بالهيكل المحوري، وتمتد بين القص ولوح الكتف.',notes:[['طرفان','Sternal end: الطرف الإنسي ناحية القص. Acromial end: الطرف الوحشي ناحية الأخرم.'],['للمذاكرة','ميّز الطرفين والجسم، ثم السطح العلوي والسفلي. جرّب العزل والدوران لرؤية شكل العظمة.']]},
scapula:{description:'عظمة مسطحة مثلثة في الجزء الخلفي من الحزام الكتفي. تتصل بالعضد عند التجويف الحقاني وبالترقوة عند الأخرم.',notes:[['ثلاث حواف وثلاث زوايا','الحواف: superior, medial, lateral. الزوايا: superior, inferior, lateral.'],['سطحان','السطح الخلفي يحمل شوكة لوح الكتف التي تفصل حفرتين؛ والسطح الأمامي يحمل subscapular fossa.'],['أجزاء مهمة','Spine: الشوكة. Acromion: الأخرم. Coracoid process: الناتئ الغرابي. Glenoid cavity: التجويف الحقاني.']]},
humerus:{description:'عظم الذراع بين الكتف والمرفق. الرأس القريب يتمفصل مع لوح الكتف، والنهاية البعيدة تشارك في مفصل المرفق.',notes:[]},radius:{description:'إحدى عظمتَي الساعد؛ تقع على جهة الإبهام في الوضع التشريحي.',notes:[]},ulna:{description:'إحدى عظمتَي الساعد؛ تقع على جهة الخنصر في الوضع التشريحي.',notes:[]}};
let mode='body',datasets={},records=[],selected=null,isolation=false,hidden=new Set(),enabled=new Set(['bone']),loaded=new Set(),busy=false,fullBounds=new THREE.Box3(),root=null,version=0,quiz=null,score={correct:0,total:0},hover=null;
const cache=new Map();
function displayName(name){return name.replace(/\.r\.?$/i,' — right').replace(/\.l\.?$/i,' — left').replace(/__FMA\d+/,'').replace(/_/g,' ');}
function arabic(name){let key=name.toLowerCase();let pair=translated.find(([en])=>key.includes(en));if(!pair)return '';let side=/right|\.r\.?$/i.test(name)?' — يمين':/left|\.l\.?$/i.test(name)?' — يسار':'';if(/rib/i.test(key)){let n=key.match(/\((\d+)/);if(n)return 'الضلع '+n[1]+side;}return pair[1]+side;}
function material(kind,name){let color=colors[kind]||colors.bone;if(kind==='organ'&&/lungs/.test(name))color='#d1939e';if(kind==='vessel'&&/vein/.test(name))color='#6099d5';return new THREE.MeshStandardMaterial({color,roughness:.6,metalness:.04,side:THREE.DoubleSide,transparent:kind==='skin',opacity:kind==='skin'?.17:1,depthWrite:kind!=='skin'});}
function addRecord(ds,object,name,kind,id,meta=null){let r={id,name:displayName(name),ar:arabic(name),kind,object,meta,meshes:[],center:new THREE.Vector3(),base:new THREE.Vector3()};object.traverse(m=>{if(m.isMesh){if(!m.geometry.attributes.normal)m.geometry.computeVertexNormals();m.material=material(kind,name);m.userData.record=r;r.meshes.push(m);}});ds.records.push(r);return r;}
function extract(ds,gltf,kind){const meshes=[];gltf.scene.traverse(n=>{if(n.isMesh)meshes.push(n);});for(const mesh of meshes){let assoc=gltf.parser.associations.get(mesh);let name=assoc?.nodes!=null?gltf.parser.json.nodes[assoc.nodes].name:mesh.name;addRecord(ds,mesh,name||mesh.name,kind,kind+':'+name);}}
async function fetchGLB(path){if(cache.has(path))return cache.get(path);let p=loader.loadAsync(path);cache.set(path,p);try{return await p;}catch(e){cache.delete(path);throw e;}}
function showLoad(message){$('loading').hidden=false;$('loadText').textContent=message;$('retry').hidden=true;}
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,3200);}
function prepare(ds){ds.root.updateMatrixWorld(true);for(const r of ds.records){r.base.copy(r.object.position);new THREE.Box3().setFromObject(r.object).getCenter(r.center);}ds.bounds=new THREE.Box3().setFromObject(ds.root);}
async function buildBody(){const ds={root:new THREE.Group(),records:[],layers:new Set(['bone'])};let gltf=await fetchGLB('./assets/overview-skeleton.glb');let skeleton=gltf.scene;extract(ds,gltf,'bone');skeleton.updateMatrixWorld(true);let box=new THREE.Box3().setFromObject(skeleton);let mirrorGroup=new THREE.Group();for(const r of [...ds.records])if(/\.r\.?$/i.test(r.object.name)||/ — right$/.test(r.name)){let clone=r.object.clone();clone.matrix.copy(r.object.matrixWorld);clone.matrix.premultiply(new THREE.Matrix4().makeScale(-1,1,1));clone.matrix.decompose(clone.position,clone.quaternion,clone.scale);mirrorGroup.add(clone);let name=r.name.replace(' — right',' — left');addRecord(ds,clone,name,'bone','bone:'+name);}
const skRoot=new THREE.Group();skRoot.add(skeleton,mirrorGroup);let widthMin=Math.min(box.min.x,-box.max.x),widthMax=Math.max(box.max.x,-box.min.x),scale=6.718155/(box.max.y-box.min.y);skRoot.scale.setScalar(scale);skRoot.position.set(-(widthMin+widthMax)*.5*scale,-3.48-box.min.y*scale,.4-(box.min.z+box.max.z)*.5*scale);ds.root.add(skRoot);prepare(ds);return ds;}
const armIds=['clavicle_right','scapula_right','humerus_right','radius_right','ulna_right'];
const muscleIds=['deltoid_right','biceps_brachii_right','triceps_brachii_right','brachialis_right','brachioradialis_right','flexor_carpi_radialis_right'];
const vesselIds=['brachial_artery_right','radial_artery_right','ulnar_artery_right','basilic_vein_right','cephalic_vein_right'];
async function addArmLayer(ds,ids,kind){await Promise.all(ids.map(async id=>{let [gltf,meta]=await Promise.all([fetchGLB('./shoulder/'+id+'.glb'),fetch('./shoulder/'+id+'.json').then(r=>{if(!r.ok)throw Error('metadata');return r.json();})]);ds.root.add(gltf.scene);addRecord(ds,gltf.scene,meta.name,kind,id,meta);}));ds.layers.add(kind);prepare(ds);}
async function buildArm(){let ds={root:new THREE.Group(),records:[],layers:new Set()};await addArmLayer(ds,armIds,'bone');return ds;}
async function activate(newMode){if(busy)return;busy=true;let token=++version;mode=newMode;showLoad(newMode==='body'?'تجهيز الهيكل العظمي…':'تجهيز نماذج الكتف والذراع…');endQuiz();try{if(!datasets[mode])datasets[mode]=await (mode==='body'?buildBody():buildArm());if(token!==version)return;dsActivate(datasets[mode]);$('loading').hidden=true;}catch(e){console.error(e);$('loadText').textContent='تعذّر تحميل النموذج. تحقق من الاتصال وأعد المحاولة.';$('retry').hidden=false;}finally{busy=false;}}
function dsActivate(ds){for(const r of records)r.object.position.copy(r.base);if(root)scene.remove(root);root=ds.root;scene.add(root);records=ds.records;selected=null;hidden.clear();isolation=false;enabled=new Set(['bone']);loaded=ds.layers;$('ghost').checked=false;$('section').checked=false;$('sectionControl').hidden=true;$('sectionAxisControl').hidden=true;$('explode').value=0;$('explodeValue').textContent='0%';controls.autoRotate=false;$('rotate').setAttribute('aria-pressed','false');fullBounds=ds.bounds.clone();$('bodyTab').classList.toggle('active',mode==='body');$('armTab').classList.toggle('active',mode==='arm');$('sceneTitle').textContent=mode==='body'?'الهيكل العظمي':'الكتف والذراع الأيمن';$('modeLabel').textContent=mode==='body'?'BODY / SKELETAL':'UPPER LIMB / RIGHT';$('emptyDetail').hidden=false;$('selectedDetail').hidden=true;$('search').value='';renderLayers();updateVisibility();renderList();fit();renderPins();}
function renderLayers(){let kinds=mode==='body'?['bone','organ','skin']:['bone','muscle','vessel'];$('layers').replaceChildren();for(const kind of kinds){let label=document.createElement('label');label.className='layer';let dot=document.createElement('i');dot.style.background=colors[kind];let text=document.createElement('span');text.textContent=kindAr[kind];let small=document.createElement('small');small.textContent=loaded.has(kind)?'3D':'تحميل عند الطلب';let check=document.createElement('input');check.type='checkbox';check.checked=enabled.has(kind);check.setAttribute('aria-label',kindAr[kind]);check.onchange=()=>toggleLayer(kind,check.checked,check);label.append(dot,text,small,check);$('layers').append(label);}}
async function toggleLayer(kind,on,input){if(on&&!loaded.has(kind)){input.disabled=true;toast('تحميل '+kindAr[kind]+'…');let ds=datasets[mode],targetMode=mode;explode(0);$('explode').value=0;try{if(mode==='arm')await addArmLayer(ds,kind==='muscle'?muscleIds:vesselIds,kind);else{let gltf=await fetchGLB(kind==='skin'?'./assets/anatomy-skin.glb':'./assets/anatomy-organs.glb');let organRoot=gltf.scene;organRoot.position.y=.054865;ds.root.add(organRoot);extract(ds,gltf,kind);ds.layers.add(kind);prepare(ds);}if(mode!==targetMode)return;records=ds.records;loaded=ds.layers;}catch(e){console.error(e);input.checked=false;toast('تعذّر تحميل الطبقة. حاول مرة أخرى.');return;}finally{input.disabled=false;}}
if(on)enabled.add(kind);else enabled.delete(kind);isolation=false;updateVisibility();renderList();renderLayers();}
function updateVisibility(){for(const r of records){let visible=enabled.has(r.kind)&&!hidden.has(r.id)&&(!isolation||r===selected);r.object.visible=visible;for(const m of r.meshes){let ghost=$('ghost').checked&&selected&&r!==selected;let skin=r.kind==='skin';m.material.transparent=skin||!!ghost;m.material.opacity=skin?.17:ghost?.14:1;m.material.depthWrite=!skin&&!ghost;m.material.clippingPlanes=$('section').checked?[clipPlane]:[];m.material.emissive.set(r===selected?0x264a28:0x000000);m.material.color.set(r===selected?'#cee98b':colors[r.kind]||colors.bone);if(r!==selected&&r.kind==='vessel'&&/vein/i.test(r.name))m.material.color.set('#6099d5');if(r!==selected&&r.kind==='organ'&&/lungs/.test(r.name))m.material.color.set('#d1939e');}}$('isolate').classList.toggle('on',isolation);$('isolate').textContent=isolation?'إنهاء العزل':'عزل الجزء';}
function renderList(){const query=$('search').value.trim().toLowerCase();let list=records.filter(r=>enabled.has(r.kind)&&(`${r.name} ${r.ar}`).toLowerCase().includes(query)).sort((a,b)=>a.name.localeCompare(b.name));$('structureList').replaceChildren();$('count').textContent=records.length+' جزءًا';$('resultCount').textContent=list.length;for(const r of list){let button=document.createElement('button');button.className='structure-row'+(selected===r?' active':'');let title=document.createElement('span');title.textContent=r.ar||r.name;button.append(title);if(r.ar){let small=document.createElement('small');small.textContent=r.name;button.append(small);}button.onclick=()=>{if(quiz){toast('اختار الإجابة من النموذج ثلاثي الأبعاد.');return;}hidden.delete(r.id);select(r);focusRecord(r);};$('structureList').append(button);}if(!list.length){let p=document.createElement('p');p.className='scope-note';p.textContent='لا توجد نتائج في الطبقات المعروضة.';$('structureList').append(p);}}
function select(r){selected=r;$('emptyDetail').hidden=true;$('selectedDetail').hidden=false;$('kindLabel').textContent=kindAr[r.kind]||'';$('arabicName').textContent=r.ar||'الجزء المحدد';$('englishName').textContent=r.name;$('speechStatus').textContent='';let study=Object.entries(notes).find(([k])=>r.name.toLowerCase().includes(k))?.[1];$('description').textContent=study?.description||(r.meta?.description||'استكشف شكل هذا الجزء وموقعه في النموذج. الشرح التفصيلي غير متاح لهذا الجزء في النسخة الحالية.');$('studyNotes').replaceChildren();for(const [title,content] of study?.notes||[]){let div=document.createElement('div');div.className='note';let strong=document.createElement('b');strong.textContent=title;let p=document.createElement('span');p.textContent=content;div.append(strong,p);$('studyNotes').append(div);}if(study){let a=document.createElement('a');a.href='https://openstax.org/books/anatomy-and-physiology-2e/pages/'+(/clavicle|scapula/i.test(r.name)?'8-1-the-pectoral-girdle':'8-2-bones-of-the-upper-limb');a.target='_blank';a.rel='noreferrer';a.textContent='المرجع: OpenStax';a.style.fontSize='12px';$('studyNotes').append(a);}updateVisibility();renderList();renderPersonal();}
function fit(box=fullBounds,dir=new THREE.Vector3(0,.04,1)){let center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3());let fov=THREE.MathUtils.degToRad(camera.fov);let distance=Math.max(size.y/(2*Math.tan(fov/2)),Math.max(size.x,size.z)/(2*Math.tan(fov/2)*camera.aspect))*1.23;distance=Math.max(distance,.15);camera.position.copy(center).add(dir.normalize().multiplyScalar(distance));controls.target.copy(center);controls.update();}
function focusRecord(r){let box=new THREE.Box3().setFromObject(r.object);fit(box,camera.position.clone().sub(controls.target));}
$('search').oninput=renderList;$('bodyTab').onclick=()=>activate('body').then(renderPins);$('armTab').onclick=()=>activate('arm').then(renderPins);$('retry').onclick=()=>activate(mode);
$('isolate').onclick=()=>{if(!selected)return;isolation=!isolation;updateVisibility();if(isolation)focusRecord(selected);else fit();};$('focus').onclick=()=>selected&&focusRecord(selected);$('hide').onclick=()=>{if(!selected)return;hidden.add(selected.id);isolation=false;updateVisibility();toast('تم الإخفاء. استعادة كل الأجزاء يعيده.');};
function restore(){hidden.clear();isolation=false;$('ghost').checked=false;$('explode').value=0;explode(0);$('section').checked=false;$('sectionControl').hidden=true;$('sectionAxisControl').hidden=true;updateVisibility();fit();}
$('restore').onclick=restore;$('ghost').onchange=updateVisibility;$('section').onchange=()=>{$('sectionControl').hidden=!$('section').checked;$('sectionAxisControl').hidden=!$('section').checked;updateClip();updateVisibility();};
function updateClip(){const axis=$('sectionAxis').value;clipPlane.normal.set(axis==='x'?-1:0,axis==='y'?-1:0,axis==='z'?-1:0);let value=Number($('sectionLevel').value)/100;clipPlane.constant=fullBounds.min[axis]+(fullBounds.max[axis]-fullBounds.min[axis])*value;}
$('sectionLevel').oninput=updateClip;
function explode(value){$('explodeValue').textContent=Math.round(value*100)+'%';let center=fullBounds.getCenter(new THREE.Vector3());let globalScale=mode==='body'?6.718155/1.7:1;for(const r of records){let dir=r.center.clone().sub(center);dir.y*=.15;let parentScale=r.object.parent.getWorldScale(new THREE.Vector3()).x;let spread=dir.multiplyScalar(value*.65/Math.abs(parentScale||globalScale));r.object.position.copy(r.base).add(spread);}root?.updateMatrixWorld(true);}
$('explode').oninput=()=>explode(Number($('explode').value)/100);
for(const button of document.querySelectorAll('[data-view]'))button.onclick=()=>{let map={front:[0,0,1],back:[0,0,-1],right:[-1,0,0],left:[1,0,0]};fit(isolation&&selected?new THREE.Box3().setFromObject(selected.object):fullBounds,new THREE.Vector3(...map[button.dataset.view]));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b===button));};
$('zoomIn').onclick=()=>{camera.position.lerp(controls.target,.2);controls.update();};$('zoomOut').onclick=()=>{camera.position.sub(controls.target).multiplyScalar(1.2).add(controls.target);controls.update();};$('resetCamera').onclick=()=>fit();$('rotate').onclick=()=>{controls.autoRotate=!controls.autoRotate;$('rotate').setAttribute('aria-pressed',String(controls.autoRotate));};
$('speak').onclick=()=>{if(!selected)return;if(!('speechSynthesis' in window)){$('speechStatus').textContent='النطق الصوتي غير متاح في هذا المتصفح.';return;}speechSynthesis.cancel();let utter=new SpeechSynthesisUtterance(selected.name.replace(/ — /g,' '));utter.lang='en-US';utter.rate=.82;let voice=speechSynthesis.getVoices().find(v=>v.lang==='en-US')||speechSynthesis.getVoices().find(v=>v.lang.startsWith('en'));if(voice)utter.voice=voice;utter.onerror=()=>{$('speechStatus').textContent='تعذّر تشغيل الصوت. تحقق من أصوات الإنجليزية على الجهاز.';};utter.onstart=()=>{$('speechStatus').textContent='جاري النطق…';};utter.onend=()=>{$('speechStatus').textContent='';};speechSynthesis.speak(utter);};
for(const b of document.querySelectorAll('[data-shortcut]'))b.onclick=()=>{let r=records.find(r=>r.name.toLowerCase().includes(b.dataset.shortcut));if(r){enabled.add(r.kind);hidden.delete(r.id);select(r);focusRecord(r);}};
let startPoint=null;
function pickHit(event){const rect=renderer.domElement.getBoundingClientRect();pointer.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);let meshes=records.filter(r=>r.object.visible&&r.kind!=='skin').flatMap(r=>r.meshes);let hit=raycaster.intersectObjects(meshes,false).find(h=>!$('section').checked||clipPlane.distanceToPoint(h.point)>=0);return hit;}
function pick(event){return pickHit(event)?.object.userData.record;}
renderer.domElement.addEventListener('pointerdown',e=>startPoint={x:e.clientX,y:e.clientY});renderer.domElement.addEventListener('pointerup',e=>{if(!startPoint||Math.hypot(e.clientX-startPoint.x,e.clientY-startPoint.y)>7)return;let hit=pickHit(e);if(pinPlacement&&hit){beginPin(hit);return;}let r=hit?.object.userData.record;if(r){if(quiz)answer(r);else select(r);}});
renderer.domElement.addEventListener('pointermove',e=>{if(e.pointerType==='touch'||e.buttons||quiz){$('hoverLabel').hidden=true;return;}let r=pick(e);hover=r;if(r){let rect=viewport.getBoundingClientRect();$('hoverLabel').textContent=r.ar||r.name;$('hoverLabel').style.left=Math.min(e.clientX-rect.left+15,viewport.clientWidth-230)+'px';$('hoverLabel').style.top=Math.min(e.clientY-rect.top+18,viewport.clientHeight-60)+'px';$('hoverLabel').hidden=false;renderer.domElement.style.cursor='pointer';}else{$('hoverLabel').hidden=true;renderer.domElement.style.cursor='grab';}});renderer.domElement.addEventListener('pointerleave',()=>{$('hoverLabel').hidden=true;});
function nextQuiz(){if(!records.length)return;restore();enabled=new Set(['bone']);updateVisibility();let keys=['clavicle','scapula','humerus','radius','ulna','femur','tibia','fibula','patella','mandible','sacrum'];let pool=records.filter(r=>r.kind==='bone'&&keys.some(k=>r.name.toLowerCase().includes(k)));if(!pool.length)return;quiz={target:pool[Math.floor(Math.random()*pool.length)],answered:false};selected=null;$('emptyDetail').hidden=false;$('selectedDetail').hidden=true;$('quiz').hidden=false;$('quizPrompt').textContent='Find: '+quiz.target.name;$('quizFeedback').textContent='اضغط على الجزء المطلوب في النموذج.';$('quizFeedback').style.color='';$('quizScore').textContent=score.correct+' / '+score.total;$('hoverLabel').hidden=true;$('quizButton').textContent='التدريب شغّال';renderList();renderLayers();updateVisibility();}
function answer(r){if(quiz.answered)return;quiz.answered=true;score.total++;let ok=r===quiz.target;if(ok)score.correct++;study.quiz.total++;if(ok)study.quiz.correct++;persist();$('quizFeedback').textContent=ok?'إجابة صحيحة 👏':'اخترت '+r.name+'. الجزء الصحيح مضاء الآن.';$('quizFeedback').style.color=ok?'#c6ef76':'#ffb7a6';$('quizScore').textContent=score.correct+' / '+score.total;select(quiz.target);focusRecord(quiz.target);}
function endQuiz(){quiz=null;$('quiz').hidden=true;$('quizButton').textContent='تدريب عملي ◎';}
$('quizButton').onclick=()=>{if(busy)return;if(quiz)endQuiz();else{score={correct:0,total:0};nextQuiz();}};$('quizNext').onclick=nextQuiz;$('quizEnd').onclick=endQuiz;
$('sourcesButton').onclick=()=>$('sources').showModal();$('closeSources').onclick=()=>$('sources').close();$('sources').onclick=e=>{if(e.target===$('sources')){let b=$('sources').getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)$('sources').close();}};
new ResizeObserver(()=>{camera.aspect=viewport.clientWidth/viewport.clientHeight;camera.updateProjectionMatrix();renderer.setSize(viewport.clientWidth,viewport.clientHeight);}).observe(viewport);
function animate(){requestAnimationFrame(animate);controls.update();renderer.render(scene,camera);updatePinPositions();}
window.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA/.test(e.target.tagName))return;if(e.key==='Escape'){pinPlacement=false;$('placePin').textContent='＋ علامة شخصية';endQuiz();if(isolation){isolation=false;updateVisibility();fit();}}if(e.key==='r')fit();});
if(document.modelContext?.registerTool){const lifetime=new AbortController();let tool={name:'select_anatomical_structure',title:'Select anatomical structure',description:'Select a loaded anatomical structure by exact ID and focus it in the 3D viewer.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input.id!=='string')throw Error('A structure ID is required.');let r=records.find(r=>r.id===input.id);if(!r)throw Error('Structure is not loaded.');if(quiz)throw Error('End the current quiz before selecting a structure.');enabled.add(r.kind);hidden.delete(r.id);select(r);focusRecord(r);renderLayers();return {id:r.id,name:r.name,scene:mode};}};try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifetime.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>lifetime.abort(),{once:true});}

// Local study workspace: no account, secrets, or backend.
const storageKey='thomas-anatomy-study-v1:'+new URL('.',import.meta.url).pathname;
let storage=null,initial;try{storage=window.localStorage;initial=loadState(storage,storageKey);}catch(e){initial={state:emptyState(),error:e.message};}
let study=initial.state,pinPlacement=false,pendingPin=null,pinElements=[];
function persist(){try{if(!storage)throw Error('Storage unavailable');saveState(storage,storageKey,study);return true;}catch(e){toast('تعذّر الحفظ في هذا المتصفح. صدّر نسخة احتياطية.');return false;}}
function recordKey(r){return mode+'::'+r.id;}
function renderPersonal(){if(!selected)return;let key=recordKey(selected);$('personalNote').value=study.notes[key]||'';let bookmarked=study.bookmarks.includes(key);$('bookmark').setAttribute('aria-pressed',String(bookmarked));$('bookmark').textContent=bookmarked?'★ في المفضلة':'☆ أضف للمفضلة';$('selectedPins').replaceChildren();for(const pin of study.pins.filter(p=>p.key===key)){let row=document.createElement('div');row.className='pin-row';let text=document.createElement('span');text.textContent=pin.label;let remove=document.createElement('button');remove.textContent='حذف';remove.onclick=()=>{study.pins=study.pins.filter(p=>p.id!==pin.id);persist();renderPersonal();renderPins();};row.append(text,remove);$('selectedPins').append(row);}renderPins();}
$('saveNote').onclick=()=>{if(!selected)return;study.notes[recordKey(selected)]=$('personalNote').value;if(persist())toast('تم حفظ ملاحظتك.');};
$('bookmark').onclick=()=>{if(!selected)return;let key=recordKey(selected);study.bookmarks=study.bookmarks.includes(key)?study.bookmarks.filter(k=>k!==key):[...study.bookmarks,key];persist();renderPersonal();};
$('placePin').onclick=()=>{if(quiz){toast('أنهِ التدريب أولًا.');return;}if(study.pins.length>=100){toast('الحد الأقصى ١٠٠ علامة شخصية.');return;}pinPlacement=!pinPlacement;$('placePin').textContent=pinPlacement?'إلغاء وضع العلامة':'＋ علامة شخصية';if(pinPlacement)toast('اضغط على الموضع الذي تريده فوق سطح النموذج.');};
function beginPin(hit){let r=hit.object.userData.record;pendingPin={id:crypto.randomUUID(),key:recordKey(r),position:r.object.worldToLocal(hit.point.clone()).toArray(),label:''};pinPlacement=false;$('placePin').textContent='＋ علامة شخصية';$('pinLabel').value='';$('pinDialog').showModal();$('pinLabel').focus();}
$('savePin').onclick=()=>{let label=$('pinLabel').value.trim();if(!pendingPin||!label){toast('اكتب اسم العلامة.');return;}study.pins.push({...pendingPin,label});pendingPin=null;persist();$('pinDialog').close();renderPins();renderPersonal();};$('cancelPin').onclick=()=>{pendingPin=null;$('pinDialog').close();};
function renderPins(){pinElements=[];$('pinOverlay').replaceChildren();for(const pin of study.pins){let r=records.find(r=>recordKey(r)===pin.key);if(!r)continue;let button=document.createElement('button');button.className='user-pin';button.textContent=pin.label;button.title='علامة شخصية — غير مراجعة';button.onclick=()=>{if(!quiz){select(r);focusRecord(r);}};$('pinOverlay').append(button);pinElements.push({pin,r,button});}}
function updatePinPositions(){if(typeof pinElements==='undefined')return;for(const {pin,r,button} of pinElements){if(!$('showPins').checked||quiz||!r.object.visible){button.hidden=true;continue;}let world=r.object.localToWorld(new THREE.Vector3(...pin.position));if($('section').checked&&clipPlane.distanceToPoint(world)<0){button.hidden=true;continue;}let p=world.project(camera);button.hidden=p.z<-1||p.z>1||Math.abs(p.x)>1||Math.abs(p.y)>1;if(!button.hidden){button.style.left=((p.x+1)*viewport.clientWidth/2)+'px';button.style.top=((-p.y+1)*viewport.clientHeight/2)+'px';}}}
function workspaceList(){let stats=study.quiz;$('studyStats').textContent=Object.values(study.notes).filter(Boolean).length+' ملاحظة · '+study.pins.length+' علامة · نتيجة التدريب الإجمالية '+stats.correct+' / '+stats.total;$('bookmarkList').replaceChildren();for(const key of study.bookmarks){let row=document.createElement('div');row.className='saved-row';let button=document.createElement('button');button.textContent=key.split('::').slice(1).join('::').replace(/^bone:/,'');button.onclick=async()=>{let [m,...parts]=key.split('::');await navigateTo(m,parts.join('::'));$('workspace').close();};let remove=document.createElement('button');remove.textContent='حذف';remove.onclick=()=>{study.bookmarks=study.bookmarks.filter(k=>k!==key);persist();workspaceList();if(selected)renderPersonal();};row.append(button,remove);$('bookmarkList').append(row);}if(!study.bookmarks.length)$('bookmarkList').textContent='لم تضف أجزاء إلى المفضلة بعد.';
$('snapshotList').replaceChildren();for(const snapshot of study.snapshots){let row=document.createElement('div');row.className='saved-row';let b=document.createElement('button');b.textContent=snapshot.name;b.onclick=async()=>{try{await restoreSnapshot(snapshot);$('workspace').close();}catch(e){toast(e.message);}};let remove=document.createElement('button');remove.textContent='حذف';remove.onclick=()=>{study.snapshots=study.snapshots.filter(s=>s.id!==snapshot.id);persist();workspaceList();};row.append(b,remove);$('snapshotList').append(row);}if(!study.snapshots.length)$('snapshotList').textContent='احفظ زاوية العرض والأجزاء الظاهرة للعودة إليها.';}
async function ensureNavigation(m){if(busy)throw Error('انتظر اكتمال تحميل النموذج.');endQuiz();if(mode!==m)await activate(m);if(!datasets[m]||root!==datasets[m].root)throw Error('تعذّر فتح النموذج.');}
async function navigateTo(m,id){try{await ensureNavigation(m);let r=records.find(r=>r.id===id);if(!r){for(const kind of (m==='arm'?['muscle','vessel']:['organ','skin'])){await toggleLayer(kind,true,{disabled:false,checked:true});r=records.find(r=>r.id===id);if(r)break;}}if(!r)throw Error('هذا الجزء غير متاح في النسخة الحالية.');enabled.add(r.kind);hidden.delete(r.id);select(r);focusRecord(r);renderLayers();renderPins();}catch(e){toast(e.message);}}
$('workspaceButton').onclick=()=>{workspaceList();$('workspace').showModal();};$('closeWorkspace').onclick=()=>$('workspace').close();
$('saveSnapshot').onclick=()=>{let name=$('snapshotName').value.trim();if(!name){toast('اكتب اسم المشهد.');return;}if(study.snapshots.length>=50){toast('الحد الأقصى ٥٠ مشهدًا.');return;}study.snapshots.push({id:crypto.randomUUID(),name,mode,camera:camera.position.toArray(),target:controls.target.toArray(),enabled:[...enabled],hidden:[...hidden],selected:selected?.id||null});if(persist())toast('تم حفظ المشهد.');$('snapshotName').value='';workspaceList();};
async function restoreSnapshot(snapshot){await ensureNavigation(snapshot.mode);restore();for(const kind of snapshot.enabled)if(!loaded.has(kind))await toggleLayer(kind,true,{disabled:false,checked:true});enabled=new Set(snapshot.enabled);hidden=new Set(snapshot.hidden);selected=records.find(r=>r.id===snapshot.selected)||null;if(selected)select(selected);else{$('selectedDetail').hidden=true;$('emptyDetail').hidden=false;}updateVisibility();renderLayers();renderList();renderPins();camera.position.fromArray(snapshot.camera);controls.target.fromArray(snapshot.target);controls.update();}
$('exportStudy').onclick=()=>{let text=JSON.stringify(validateState(study),null,2);let url=URL.createObjectURL(new Blob([text],{type:'application/json'}));let a=document.createElement('a');a.href=url;a.download='thomas-anatomy-study.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('importStudy').onchange=async e=>{let file=e.target.files[0];if(!file)return;try{if(file.size>5*1024*1024)throw Error('ملف المذاكرة أكبر من الحد المسموح.');let incoming=validateState(JSON.parse(await file.text()));let mergedNotes={...study.notes,...incoming.notes},mergedBookmarks=[...new Set([...study.bookmarks,...incoming.bookmarks])];let merge=(a,b)=>[...new Map([...a,...b].map(x=>[x.id,x])).values()];let combined={...study,notes:mergedNotes,bookmarks:mergedBookmarks,pins:merge(study.pins,incoming.pins),snapshots:merge(study.snapshots,incoming.snapshots),foundation:{known:[...new Set([...study.foundation.known,...incoming.foundation.known])]},quiz:{correct:Math.max(study.quiz.correct,incoming.quiz.correct),total:Math.max(study.quiz.total,incoming.quiz.total)}};study=validateState(combined);persist();workspaceList();renderPins();if(selected)renderPersonal();toast('تم استيراد المذاكرة ودمجها.');}catch(err){toast(err.message||'تعذّر قراءة الملف.');}finally{e.target.value='';}};
$('sectionAxis').onchange=()=>{updateClip();updateVisibility();};
let installPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('installApp').hidden=false;});$('installApp').onclick=async()=>{if(!installPrompt)return;await installPrompt.prompt();installPrompt=null;$('installApp').hidden=true;};
$('downloadOffline').onclick=async()=>{if(!('serviceWorker' in navigator)||!('caches' in window)){toast('هذا المتصفح لا يدعم النسخة دون اتصال.');return;}let button=$('downloadOffline');button.disabled=true;try{let paths=await fetch('./offline-assets.json').then(r=>{if(!r.ok)throw Error('تعذّر قراءة قائمة الملفات.');return r.json();});let cache=await caches.open('thomas-anatomy-v3'),count=0,next=0;await Promise.all(Array.from({length:4},async()=>{while(next<paths.length){let path=paths[next++];let url=new URL(path,import.meta.url);let response=await fetch(url);if(!response.ok)throw Error('تعذّر تحميل '+path);await cache.put(url,response);count++;$('offlineStatus').textContent='تم تنزيل '+count+' / '+paths.length+' ملفًا';}}));await Promise.race([navigator.serviceWorker.ready,new Promise((_,reject)=>setTimeout(()=>reject(Error('Service worker unavailable')),20000))]);if(navigator.storage?.persist)await navigator.storage.persist();$('offlineStatus').textContent='الملفات جاهزة. افتح التطبيق مرة أخرى قبل قطع الاتصال للتأكد من تشغيله.';toast('اكتمل تنزيل النماذج.');}catch(e){$('offlineStatus').textContent='لم يكتمل التنزيل. الملفات الناجحة محفوظة؛ أعد المحاولة.';}finally{button.disabled=false;}};
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>{$('offlineStatus').textContent='تعذّر تجهيز العمل دون اتصال في هذا المتصفح.';});
if(initial.error)setTimeout(()=>toast('تعذّر استعادة الحفظ السابق؛ يمكنك استيراد نسخة احتياطية.'),1000);
setupFoundation({getKnown:()=>study.foundation.known,setKnown:known=>{study.foundation.known=known;persist();},onAnswer:ok=>{study.quiz.total++;if(ok)study.quiz.correct++;persist();},showBone:async bone=>{await ensureNavigation('arm');restore();enabled=new Set(['bone']);const r=records.find(r=>r.id===bone+'_right');if(!r)throw Error('تعذّر فتح العظمة.');select(r);isolation=true;updateVisibility();focusRecord(r);renderLayers();renderPins();}});
animate();
activate('body').then(renderPins);
