import {test} from 'node:test';import assert from 'node:assert/strict';
import {regionOf,landmarks} from '../anatomy-view.mjs';
import * as THREE from '../vendor/build/three.module.js';
import {SoftwareRenderer} from '../software-renderer.mjs';
test('regional isolation separates similar hand and foot names',()=>{for(const [name,region] of [['Scapula — left','upper'],['Distal phalanx of fifth finger of foot — right','lower'],['Distal phalanx of 5th finger — right','upper'],['Costal cart of 10th rib — right','thorax'],['Atlas (C1)','spine'],['Parietal bone left','skull']])assert.equal(regionOf(name),region);});
test('teaching anchors belong only to supplied detailed bones and have finite positions',()=>{assert.deepEqual(Object.keys(landmarks).sort(),['clavicle_right','scapula_right']);for(const pins of Object.values(landmarks))for(const pin of pins){assert.equal(pin.position.length,3);assert.ok(pin.position.every(Number.isFinite));assert.ok(pin.view.some(x=>x!==0));}});
test('CPU renderer draws actual mesh geometry without WebGL and updates after camera changes',()=>{let fills=0,clears=0;const ctx={setTransform(){},clearRect(){clears++;},beginPath(){},moveTo(){},lineTo(){},closePath(){},fill(){fills++;},stroke(){}};globalThis.document={createElement:()=>({style:{},getContext:()=>ctx})};const renderer=new SoftwareRenderer();renderer.setPixelRatio(2);renderer.setSize(640,480);assert.equal(renderer.domElement.width,1280);assert.equal(renderer.domElement.style.width,"640px");const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(40,640/480,.01,100);camera.position.z=5;const mesh=new THREE.Mesh(new THREE.BoxGeometry(),new THREE.MeshStandardMaterial({color:'#f2eee4'}));scene.add(mesh);renderer.render(scene,camera);assert.ok(fills>0);const first=clears;renderer.render(scene,camera);assert.equal(clears,first);camera.position.x=.2;renderer.render(scene,camera);assert.ok(clears>first);mesh.visible=false;renderer.render(scene,camera);assert.ok(clears>first+1);delete globalThis.document;});

test('selection metadata stays outside serializable mesh data so mirrored bones clone safely',()=>{const mesh=new THREE.Mesh(new THREE.BoxGeometry(),new THREE.MeshStandardMaterial());const record={object:mesh,meshes:[mesh]},byMesh=new WeakMap();byMesh.set(mesh,record);const clone=mesh.clone();assert.ok(clone.isMesh);assert.equal(byMesh.get(mesh),record);assert.equal(byMesh.get(clone),undefined);});
