import {test} from 'node:test';
import assert from 'node:assert/strict';
import {cards,questions,shuffled,setupFoundation} from '../foundation.mjs';
import {emptyState,validateState,loadState,saveState} from '../state.mjs';
test('old backups keep their notes while new review progress round trips',()=>{const old=emptyState();delete old.foundation;old.notes['arm::scapula_right']='سكشن';assert.deepEqual(validateState(old).foundation,{known:[]});const current=validateState(old);current.foundation.known=['sternal','conoid','sternal'];const store=new Map(),storage={getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v)};saveState(storage,'study',current);assert.deepEqual(loadState(storage,'study').state.foundation.known,['sternal','conoid']);assert.equal(loadState(storage,'study').state.notes['arm::scapula_right'],'سكشن');assert.throws(()=>validateState({...current,foundation:{known:[null]}}));});
test('question data has exactly one valid answer and sources; shuffle preserves inputs',()=>{assert.equal(new Set(cards.map(c=>c.id)).size,cards.length);assert.equal(new Set(questions.map(q=>q.id)).size,questions.length);for(const q of questions){assert.ok(q.answer>=0&&q.answer<q.options.length);assert.equal(new Set(q.options).size,4);assert.match(q.source,/^https:\/\//);}const original=[1,2,3,4],result=shuffled(original,()=>0);assert.deepEqual(original,[1,2,3,4]);assert.deepEqual([...result].sort(),original);});
test('review reveal, filter, quiz scoring and failed/successful 3D navigation',async()=>{
 class Element{constructor(){this.children=[];this.hidden=false;this.disabled=false;this.textContent='';this.listeners={};this.classList={add:()=>{}};}replaceChildren(...children){this.children=children;}append(e){this.children.push(e);}addEventListener(name,fn){this.listeners[name]=fn;}showModal(){this.open=true;}close(){this.open=false;this.listeners.close?.();}}
 const elements=new Map();globalThis.document={getElementById:id=>{if(!elements.has(id))elements.set(id,new Element());return elements.get(id);},createElement:()=>new Element()};globalThis.window={};const el=id=>document.getElementById(id);let known=[],scores=[],opened=[],fail=true;
 setupFoundation({getKnown:()=>known,setKnown:v=>known=v,onAnswer:ok=>scores.push(ok),showBone:async bone=>{if(fail)throw Error('load failed');opened.push(bone);}});
 el('foundationButton').onclick();assert.equal(el('foundationTerm').textContent,'Sternal end');assert.equal(el('foundationAnswer').hidden,true);assert.equal(el('foundationKnown').disabled,true);
 el('foundationReveal').onclick();el('foundationKnown').onclick();assert.deepEqual(known,['sternal']);el('foundationUnknown').onchange({target:{checked:true}});assert.equal(el('foundationTerm').textContent,'Acromial end');
 await el('foundationShowBone').onclick();assert.equal(el('foundation').open,true);assert.equal(el('foundationSpeechStatus').textContent,'load failed');fail=false;await el('foundationShowBone').onclick();assert.deepEqual(opened,['clavicle']);assert.equal(el('foundation').open,false);
 el('foundationStartQuiz').onclick();for(let i=0;i<questions.length;i++){const q=questions.find(q=>q.prompt===el('foundationQuizPrompt').textContent),button=el('foundationQuizOptions').children.find(b=>b.textContent===q.options[q.answer]);button.onclick();button.onclick();assert.equal(el('foundationQuizSource').hidden,false);el('foundationQuizNext').onclick();}assert.equal(scores.length,10);assert.ok(scores.every(Boolean));assert.equal(el('foundationQuizScore').textContent,'نتيجتك 10 / 10');assert.equal(el('foundationQuizResult').hidden,false);
 delete globalThis.document;delete globalThis.window;
});
